version: "3"
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-password
    volumes:
      - db:/var/lib/mysql
  php:
    image: chsergeig/ts3-php
    volumes:
      - php:/var/www/html
    depends_on:
      - mysql
  web:
    image: chsergeig/ts3-web
    depends_on:
      - php
    ports:
      - "9999:80"
volumes:
  db: {}
  php: {}
